// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Autumn_UIML.Model
{
    public class ModelInput
    {
        [ColumnName("Keyword"), LoadColumn(0)]
        public string Keyword { get; set; }


        [ColumnName("Class"), LoadColumn(1)]
        public string Class { get; set; }


        [ColumnName("newcode"), LoadColumn(2)]
        public string Newcode { get; set; }


        [ColumnName("Code"), LoadColumn(3)]
        public string Code { get; set; }


    }
}
